version: '3.8'

services:
  zap:
    build:
      context: ./Zap
    ports:
      - "8081:8081"
    networks:
      - zapnet

  dotnetapi:
    build:
      context: ./YourDotNetApi
    ports:
      - "5000:80"
    networks:
      - zapnet
    depends_on:
      - zap
    environment:
      - ZAP_BASE_URL=http://zap:8081

networks:
  zapnet:
    driver: bridge
